### ISSUE TITLE
After the image was compressed, was rotated

### ISSUE THREAD

**Issue by william0119** [wuwhs/js-image-compressor#1]
type: 'jpg'
size: 6.42MB
After the image was compressed, was rotated

**Comment by wuwhs** [comment]
Thank you for your feedback, because some iOS browsers will render the image in its orientation, for this problem I will get the orientation by reading the image Exif to restore its rotation.

**Comment by wuwhs** [comment]
> type: 'jpg'
> size: 6.42MB
> After the image was compressed, was rotated

add `redressOrientation ` option to cover this situation

**Comment by MrZhongFF** [comment]
Is there a way to tell whether I shoud add redressOrientation: false  ? As I know, some old browser doesn't respect EXIF orientation

**Comment by wuwhs** [comment]
catch this situation in v2.0 yet
