### ISSUE TITLE
压缩过程中FileReader报错是为什么

### ISSUE THREAD

**Issue by chenshu-97** [wuwhs/js-image-compressor#4]
typeError: Failed to execute 'readAsArrayBuffer' on 'FileReader': parameter 1 is not of type 'Blob'.
    at eval (image-compressor.js?d3a3:1137)
    at MockXMLHttpRequest.http.onload (image-compressor.js?d3a3:1105)
    at MockXMLHttpRequest.dispatchEvent (mock.js?96eb:8476)
    at XMLHttpRequest.handle (mock.js?96eb:8304)
eval @ image-compressor.js?d3a3:1137
http.onload @ image-compressor.js?d3a3:1105
dispatchEvent @ mock.js?96eb:8476
handle @ mock.js?96eb:8304
load (async)
open @ mock.js?96eb:8315
objectURLToBlob @ image-compressor.js?d3a3:1101
getImageData @ image-compressor.js?d3a3:1136
EXIF.getData @ image-compressor.js?d3a3:1726
_proto.getOrientation @ image-compressor.js?d3a3:336
_proto.getParsedOrientationInfo @ image-compressor.js?d3a3:323
eval @ image-compressor.js?d3a3:189
image.onload @ image-compressor.js?d3a3:561
load (async)
util.file2Image @ image-compressor.js?d3a3:560
_proto.init @ image-compressor.js?d3a3:180
ImageCompressor @ image-compressor.js?d3a3:156
compressImg @ UploadMaterial.vue?d8a7:82
fileChange @ UploadMaterial.vue?d8a7:47
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6917

**Comment by wuwhs** [comment]
v2.0 已修复这个问题，增加catch意外情景
