### ISSUE TITLE
为什么有的图片 不成功呢？而且也不走error的回调。demo也这样

### ISSUE THREAD

**Issue by LCBbest** [wuwhs/js-image-compressor#5]
为什么有的图片 不成功呢？而且也不走error的回调。demo也这样
![image](https://user-images.githubusercontent.com/12879534/123243005-2e22e380-d515-11eb-9066-637454e4f8f1.png)
![image](https://user-images.githubusercontent.com/12879534/123243043-3713b500-d515-11eb-9ffb-510a5d3fb0f9.png)

**Comment by wuwhs** [comment]
v2.0 fix this bug
